package com.utub.ui.player

import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.draw.clip
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import com.utub.extractor.SubtitleTrack
import com.utub.playback.PlayerStateHolder
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject

/**
 * 화질 선택·자막(CC) 칩 (2차 이관분 — docs/06).
 * 기존 PlayerViewModel 무수정 — StateHolder 경유로 서비스가 반영 (개발 원칙):
 * 화질 = 위치 유지 재해석, 자막 = 트랙 선택만 변경(재생 무중단).
 */
@HiltViewModel
class QualityCcViewModel @Inject constructor(
    private val stateHolder: PlayerStateHolder,
) : ViewModel() {
    val quality = stateHolder.preferredQuality
    val availableQualities = stateHolder.availableQualities
    val subtitleLanguage = stateHolder.subtitleLanguage
    val availableSubtitles = stateHolder.availableSubtitles

    fun setQuality(height: Int) = stateHolder.setPreferredQuality(height)
    fun setSubtitle(languageTag: String?) = stateHolder.setSubtitleLanguage(languageTag)
}

/** 화질 칩: "자동" 또는 "720p" — 탭하면 가용 화질 목록 */
@Composable
fun QualityChipCompact(
    quality: Int,
    available: List<Int>,
    onSelected: (Int) -> Unit,
    tint: Color = MaterialTheme.colorScheme.onSurfaceVariant,
) {
    var open by remember { mutableStateOf(false) }
    Box(modifier = Modifier.padding(horizontal = 3.dp)) {
        Text(
            if (quality > 0) "${quality}p" else "자동",
            style = MaterialTheme.typography.labelSmall,
            color = tint,
            modifier = Modifier
                .clip(RoundedCornerShape(6.dp))
                .border(1.dp, tint.copy(alpha = 0.55f), RoundedCornerShape(6.dp))
                .clickable { open = true }
                .padding(horizontal = 8.dp, vertical = 2.dp),
        )
        DropdownMenu(expanded = open, onDismissRequest = { open = false }) {
            DropdownMenuItem(
                text = { Text(if (quality == 0) "자동 ✓" else "자동") },
                onClick = { onSelected(0); open = false },
            )
            available.forEach { h ->
                DropdownMenuItem(
                    text = { Text(if (quality == h) "${h}p ✓" else "${h}p") },
                    onClick = { onSelected(h); open = false },
                )
            }
        }
    }
}

/** 자막(CC) 칩: 켜짐 = primary 색. 탭하면 언어 목록 + 끄기 */
@Composable
fun CcChipCompact(
    currentLanguage: String?,
    tracks: List<SubtitleTrack>,
    onSelected: (String?) -> Unit,
    activeTint: Color = MaterialTheme.colorScheme.primary,
    inactiveTint: Color = MaterialTheme.colorScheme.onSurfaceVariant,
) {
    var open by remember { mutableStateOf(false) }
    Box(modifier = Modifier.padding(horizontal = 3.dp)) {
        val ccTint = if (currentLanguage != null) activeTint else inactiveTint
        Text(
            "CC",
            style = MaterialTheme.typography.labelSmall,
            color = ccTint,
            modifier = Modifier
                .clip(RoundedCornerShape(6.dp))
                .border(1.dp, ccTint.copy(alpha = 0.55f), RoundedCornerShape(6.dp))
                .clickable { open = true }
                .padding(horizontal = 8.dp, vertical = 2.dp),
        )
        DropdownMenu(expanded = open, onDismissRequest = { open = false }) {
            DropdownMenuItem(
                text = { Text(if (currentLanguage == null) "자막 끄기 ✓" else "자막 끄기") },
                onClick = { onSelected(null); open = false },
            )
            tracks.forEach { t ->
                val label = t.displayName + if (t.isAutoGenerated) " (자동)" else ""
                DropdownMenuItem(
                    text = { Text(if (currentLanguage == t.languageTag) "$label ✓" else label) },
                    onClick = { onSelected(t.languageTag); open = false },
                )
            }
        }
    }
}
