package com.utub.extractor

/** 검색 결과·연관 영상·피드에 공통으로 쓰이는 영상 요약 정보 */
data class VideoSummary(
    val videoId: String,
    val title: String,
    val channelName: String,
    val thumbnailUrl: String?,
    val durationMs: Long,
    val viewCount: Long? = null,
    val uploadedText: String? = null,
    /** 채널 아바타 (검색 세로 카드용 — 5차) */
    val uploaderAvatarUrl: String? = null,
)

/** 스트림 해석 결과. URL은 수 시간 내 만료되므로 절대 영속화하지 않는다 (docs/04 4절) */
data class ResolvedStreams(
    val videoId: String,
    val title: String,
    val channelName: String,
    val thumbnailUrl: String?,
    val durationMs: Long,
    val muxedStreams: List<VideoTrack>,   // 영상+소리 합쳐진 스트림
    val videoOnlyStreams: List<VideoTrack>,
    val audioStreams: List<AudioTrack>,
    val related: List<VideoSummary>,
    /** 라이브 스트림 여부 — true면 [liveUrl](HLS 매니페스트)로 재생, 트랙 선택 우회 */
    val isLive: Boolean = false,
    val liveUrl: String? = null,
    /** 자막 트랙 (언어당 1개 — 일반 자막 우선, 없으면 자동 생성) */
    val subtitles: List<SubtitleTrack> = emptyList(),
    // ── 상세화면 채널 정보 (5차-C) — 없으면 UI에서 생략 ──
    val uploaderAvatarUrl: String? = null,
    val uploaderUrl: String? = null,
    val subscriberCount: Long = -1,
    val viewCount: Long = -1,
    val likeCount: Long = -1,
    val description: String? = null,
)

data class VideoTrack(
    val url: String,
    val mimeType: String?,
    val heightPx: Int,          // 예: 360, 720, 1080
    val isVideoOnly: Boolean,
)

data class AudioTrack(
    val url: String,
    val mimeType: String?,
    val averageBitrate: Int,    // kbps
)

/** 추출 실패 사유를 도메인 예외로 구분 (TC-EXT-02) */
sealed class ExtractException(message: String, cause: Throwable? = null) : Exception(message, cause) {
    class Unavailable(val reason: Reason, cause: Throwable? = null) :
        ExtractException("content unavailable: $reason", cause) {
        enum class Reason { PRIVATE, DELETED, AGE_RESTRICTED, GEO_BLOCKED, PAID, LIVE_UNSUPPORTED, UNKNOWN }
    }
    class RateLimited(cause: Throwable? = null) : ExtractException("rate limited (429)", cause)
    class Network(cause: Throwable? = null) : ExtractException("network error", cause)
    class Parse(cause: Throwable? = null) : ExtractException("parse error", cause)
}

/** N-03: 추출 엔진 계약. 구현체(NewPipe)는 이 인터페이스 뒤에 격리된다 */
interface StreamExtractor {
    suspend fun resolveStreams(videoId: String): ResolvedStreams
    suspend fun search(query: String): List<VideoSummary>
    suspend fun suggest(query: String): List<String>
    /** 비로그인 홈 피드: 인기/급상승 (SCR-100) */
    suspend fun trending(): List<VideoSummary>

    /** 댓글 조회 (5차-C) — [page] null이면 첫 페이지, 아니면 이전 결과의 nextPage */
    suspend fun comments(videoId: String, page: Any? = null): CommentsPage

    /** 피드/검색 노출 국가 변경. null이면 기기 로캘. 변경 시 캐시 초기화 */
    fun setContentCountry(countryCode: String?)
}

/** 자막 트랙 (2차 이관분 — CC) */
data class SubtitleTrack(
    val url: String,
    val mimeType: String?,
    val languageTag: String,    // 예: "ko", "en"
    val displayName: String,    // 예: "한국어"
    val isAutoGenerated: Boolean,
)

/** 댓글 (5차-C — 보기 전용, 대댓글 제외) */
data class CommentData(
    val author: String,
    val avatarUrl: String?,
    val text: String,
    val likeCount: Int,
    val publishedText: String?,
    val isPinned: Boolean,
)

/** 댓글 페이지 (더보기 페이지네이션) */
data class CommentsPage(
    val comments: List<CommentData>,
    val nextPage: Any?,          // NewPipe Page 토큰 (불투명)
    val disabled: Boolean = false,
)
